### ISSUE TITLE
Can no longer print text partially off screen in latest updates

### ISSUE THREAD

**Issue by fOmey** [gavinlyonsrepo/ER_OLEDM1_CH1115#1]
I have a loop that scrolls text across the screen which requires the cursor to be set to below zero values to create the illusion text is scrolling off screen, this is no longer possible in the latest updates.

The last known working version is 1.3.3, it is no longer possible in the latest updates.

Not sure if this was originally a bug or unintended behavior but it was very useful for scrolling text loops.

Any assistance would be appreciated.

**Comment by fOmey** [comment]
I've been working around this by removing the `CH1115_CharScreenBounds` check from `drawChar` function.

I understand my use case is unique and the behavior probably wasn't originally intended, if that's the case feel free to close this issue and I'll happily comment out the check in my local library.

**Comment by gavinlyonsrepo** [comment]
Hi 

No, its not a bug. Its not supposed to print partial characters. 

Are you horizontal scrolling or vertical scrolling?

If you are horizontal  scrolling there is a horizontal scroll command that scrolls the entire screen.

**Comment by fOmey** [comment]
Appreciate the reply, seeing it's unintended behavior I'll close this off.

Thank you for the continued support to the project.
